#!/bin/bash

############################### The parameters you need to rewrite  ##############################
# The phenotype file and the column name of the phenotype you want to analysis
pheno_file="/XYFS02/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_1/Projects/20260514_S256rrbs/input/pheno_M.csv"
column=7
# NOTICE: The name should be the same as the column name in the pheno_file
name="ASD"
# HERE!  You need to check the input file (CG, CHG, CHH) that you need to analysis
inputfile="/XYFS02/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_1/Projects/20260514_S256rrbs/input/Control_vs_Case_CG_input.txt"


########################  The parameters you don't need to rewrite, just keep them as they are  #####################
# threads
threads=64
# The output path
calling_dir="01.DMR_DMC_calling"
tools="/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_1/BIGDATA2/gzfezx_shhli_1/softwares/metilene_v0.2-8"
original_pheno_file="/XYFS02/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_1/Projects/20260514_S256rrbs/input/pheno_M.csv"

